export const STEP_VIDEO_MAP: Record<string, string> = {
  "Push-ups – 45 seconds": "/videos/push_up.mp4",
  "Tricep dips using chair – 45 seconds": "/videos/tricep_dip.mp4",
  "Arm circles – 1 minute": "/videos/arm_circles.mp4",
  "Plank shoulder taps – 45 seconds": "",
  "Rest 1 minute and repeat twice": "",
  "Burpees – 30 seconds": "/videos/burpee.mp4",
  "Squat jumps – 30 seconds": "/videos/squat_jump.mp4",
  "Plank – 1 minute": "/videos/plank.mp4",
  "Rest – 45 seconds, repeat twice": "",
  "Lunges – 45 seconds each leg": "/videos/lunge.mp4",
  "Side plank – 30 seconds each side": "/videos/side_plank.mp4",
  "Bird-dog – 1 minute": "/videos/bird_dog.mp4",
  "Push-ups (knee optional) – 30 seconds": "/videos/push_up.mp4",
  "Glute bridge – 45 seconds": "/videos/glute_bridge.mp4",
  "Plank – 30 seconds": "/videos/plank.mp4",
  "Rest – 30 seconds, repeat twice": "",
  "Neck stretch – 30 seconds": "",
  "Chest opener – 1 minute": "",
  "Shoulder rolls – 30 seconds": "/videos/shoulder_rolls.mp4",
  "Arm circles (slow) – 1 minute": "/videos/arm_circles.mp4",
  "Child's pose – 2 minutes": "/videos/childspose.mp4",
  "Cat-cow – 1 minute": "/videos/cat_cow.mp4",
  "Downward dog – 1 minute": "/videos/downward_dog.mp4",
  "Low lunge – 1 minute each side": "/videos/lunge.mp4",
  "Seated forward fold – 2 minutes": "/videos/seated_fwd_streatch.mp4",
  "Supine twist – 1 minute each side": "/videos/supine_twist.mp4",
  "Savasana – 3 minutes": "",
  "Squats – 1 minute": "/videos/squat.mp4",
  "Reverse lunges – 1 minute": "/videos/reverse_lunges.mp4",
  "Calf raises – 1 minute": "/videos/calf_raise.mp4",
  "Wall sit – 45 seconds": "/videos/wall_sit.mp4",
  "Repeat sequence twice with 1 minute rest between": "",
  "Standing knee raises – 1 minute": "/videos/high_knee_low_impact.mp4",
  "Pelvic tilts – 1 minute": "/videos/pelvic_tilts.mp4",
  "Side-lying leg lifts – 1 minute each side": "/videos/side_lying_legraise.mp4",
  "March in place – 1 minute": "/videos/marching_in_pace.mp4",
  "Side steps – 1 minute": "/videos/side_step.mp4",
  "High knees (low impact) – 30 seconds": "/videos/high_knee_low_impact.mp4",
  "Butt kicks – 30 seconds": "",
  "Repeat sequence two more times": "",
  "Crunches – 45 seconds": "/videos/crunches.mp4",
  "Bicycle crunch – 30 seconds": "/videos/bicycle_crunch.mp4",
  "Leg raises – 30 seconds": "/videos/leg_raise.mp4",
  "Rest – 1 minute, repeat twice": "",
  "Box breathing – 2 minutes": "",
  "4-7-8 breathing – 2 minutes": "",
  "Body scan meditation – 4 minutes": "",
  "Bird-dog (slow) – 1 minute": "/videos/bird_dog.mp4",
  "Gentle ab engagement – 1 minute": "",
  "Neck rotations – 30 seconds": "/videos/neck_rotation.mp4",
  "Cat-cow stretch – 1 minute": "/videos/cat_cow.mp4",
  "Hip circles – 1 minute": "/videos/hip_circles.mp4",
  "Ankle mobility – 1 minute": "",
  "Gentle forward fold – 1 minute": "",
  // Note: file is named 'hamstring streach.mp4' (typo in file)
  "Hamstring stretch – 1 minute each side": "/videos/hamstring streach.mp4",
  "Quad stretch – 1 minute each side": "/videos/quad_streatch.mp4",
};
